# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Pdp\ChorusProClient:
        arguments:
            $chorusProBaseUrl: '%env(CHORUS_PRO_BASE_URL)%'
            $chorusProOauthUrl: '%env(CHORUS_PRO_OAUTH_URL)%'
            $chorusProClientId: '%env(CHORUS_PRO_CLIENT_ID)%'
            $chorusProClientSecret: '%env(CHORUS_PRO_CLIENT_SECRET)%'
            $chorusProTechLogin: '%env(CHORUS_PRO_TECH_LOGIN)%'
            $chorusProTechPassword: '%env(CHORUS_PRO_TECH_PASSWORD)%'

    App\Controller\CompanyLogoController:
        arguments:
            $uploadDir: '%kernel.project_dir%/var/uploads/logos'

    App\Service\Invoice\InvoiceArchiver:
        arguments:
            $s3Bucket: '%env(S3_BUCKET)%'
            $s3Region: '%env(S3_REGION)%'
            $s3Endpoint: '%env(S3_ENDPOINT)%'
            $s3Key: '%env(S3_KEY)%'
            $s3Secret: '%env(S3_SECRET)%'

    App\Controller\ReceiptUploadController:
        arguments:
            $receiptUploadDir: '%kernel.project_dir%/var/uploads/receipts'

    App\Service\Ocr\OcrExtractor:
        arguments:
            $environment: '%kernel.environment%'
