sonar.organization=pierrearthurdemengel
sonar.projectKey=pierrearthurdemengel_Factura

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/cypress
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dev-dist/**,**/dist/**

# PHP
sonar.php.coverage.reportPaths=backend/coverage.xml

# TypeScript / JavaScript
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
