lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # Duree de vie courte : 15 minutes
    token_ttl: 900
    # Identifiant utilisateur dans le payload (claim du JWT)
    user_id_claim: sub
